"""visdrone dataset.

Most of this folder was autogenerated by tensorflow_datasets.
The important piece of code that I wrote to handle conversion of the dataset
is in download_dataset.py
"""

from .visdrone import Visdrone
